In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
from sklearn.ensemble import IsolationForest
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn import metrics

In [2]:
df = pd.read_csv("C:\\Users\\adity\\OneDrive\\Desktop\\IBM\\AB1_data.csv")

In [3]:
df.describe()

                No.          Time        Length
count  11677.000000  11677.000000  11677.000000
mean    5839.000000     34.448821    557.492935
std     3371.003881     19.705895   1058.157517
min        1.000000      0.000000     42.000000
25%     2920.000000     19.124251     60.000000
50%     5839.000000     32.360053     60.000000
75%     8758.000000     50.588549     74.000000
max    11677.000000     67.263828   8523.000000

In [4]:
df.isnull().sum().sum()

0

In [5]:
df.head()

,No.,Time,Source,Destination,Protocol,Length,Info
0,1,0.000000,HewlettP_81:05:00,Broadcast,ARP,60,Who has 172.17.18.180? Tell 172.17.18.254
1,2,0.004066,106.208.137.231,172.17.18.5,TLSv1.2,1231,Application Data
2,3,0.004626,172.17.18.5,106.208.137.231,TLSv1.2,615,"Application Data, Application Data"
3,4,0.008470,HewlettP_81:05:00,Broadcast,ARP,60,Who has 172.17.18.179? Tell 172.17.18.254
4,5,0.026256,HewlettP_81:05:00,Broadcast,ARP,60,Who has 172.17.18.182? Tell 172.17.18.254

In [6]:
df.drop(['Info'] , axis = 1,inplace=True)

In [7]:
df.drop(['No.'] , axis = 1,inplace=True)

In [8]:
df.head()

       Time             Source      Destination Protocol  Length
0  0.000000  HewlettP_81:05:00        Broadcast      ARP      60
1  0.004066    106.208.137.231      172.17.18.5  TLSv1.2    1231
2  0.004626        172.17.18.5  106.208.137.231  TLSv1.2     615
3  0.008470  HewlettP_81:05:00        Broadcast      ARP      60
4  0.026256  HewlettP_81:05:00        Broadcast      ARP      60

In [9]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
print("Shape of x:", x.shape)
print("Shape of y:", y.shape)

Shape of x: (11677, 4)
Shape of y: (11677,)

In [11]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelEncoder_X = LabelEncoder()
x[:,1] = labelEncoder_X.fit_transform(x[:,1])
x[:,2] = labelEncoder_X.fit_transform(x[:,2])
x[:,3] = labelEncoder_X.fit_transform(x[:,3])

In [12]:
onehotencoder = OneHotEncoder(categorical_features = [0,1,2,3])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\adity\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\adity\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [28]:
class clust():
    def _load_data(self, sklearn_load_ds):
        data = sklearn_load_ds
        X = pd.read_csv("C:\\Users\\adity\\OneDrive\\Desktop\\IBM\\AB1_data.csv")
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(x, y, test_size=0.3, random_state=42)
        
        
    def __init__(self, sklearn_load_ds):
        self._load_data(sklearn_load_ds)
    
    
    def classify(self, model=LogisticRegression(random_state=42)):
        model.fit(self.X_train, self.y_train)
        y_pred = model.predict(self.X_test)
        print('Accuracy: {}'.format(accuracy_score(self.y_test, y_pred)))
        cm_train = metrics.classification_report(y_pred , self.y_test)
        print(cm_train)


    def Kmeans(self, output='add'):
        n_clusters = len(np.unique(self.y_train))
        clf = KMeans(n_clusters = n_clusters, random_state=42)
        clf.fit(self.X_train)
        y_labels_train = clf.labels_
        y_labels_test = clf.predict(self.X_test)
        if output == 'add':
            self.X_train['km_clust'] = y_labels_train
            self.X_test['km_clust'] = y_labels_test
        elif output == 'replace':
            self.X_train = y_labels_train[:, np.newaxis]
            self.X_test = y_labels_test[:, np.newaxis]
        else:
            raise ValueError('output should be either add or replace')
        return self
clust(load_digits()).classify()

C:\Users\adity\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\adity\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

Accuracy: 0.8855593607305936
              precision    recall  f1-score   support

          42       0.00      0.00      0.00         0
          54       0.23      1.00      0.38         3
          60       1.00      0.99      1.00      1831
          62       0.00      0.00      0.00         0
          66       0.92      0.92      0.92       760
          74       0.03      0.50      0.06         2
          75       0.00      0.00      0.00         0
          77       0.00      0.00      0.00         5
          78       0.30      0.84      0.44        19
          86       0.00      0.00      0.00         0
          90       0.33      0.20      0.25         5
          91       0.00      0.00      0.00         1
          92       1.00      1.00      1.00        10
          94       0.45      0.36      0.40        14
          97       0.00      0.00      0.00         0
         117       0.25      0.11      0.15        28
         128       0.00      0.00      0.00         0
         135       0.00      0.00      0.00         0
         144       0.00      0.00      0.00         0
         172       0.00      0.00      0.00         0
         180       0.00      0.00      0.00         2
         183       0.00      0.00      0.00         0
         192       0.25      0.14      0.18         7
         203       0.00      0.00      0.00         3
         211       0.00      0.00      0.00         0
         236       0.00      0.00      0.00         0
         247       0.00      0.00      0.00         0
         254       0.00      0.00      0.00         0
         276       0.00      0.00      0.00         0
         282       0.00      0.00      0.00         0
         305       0.00      0.00      0.00         0
         306       0.00      0.00      0.00         0
         307       0.00      0.00      0.00         0
         311       0.00      0.00      0.00         0
         314       0.00      0.00      0.00         0
         318       0.00      0.00      0.00         0
         328       0.00      0.00      0.00         0
         333       0.00      0.00      0.00         0
         340       0.00      0.00      0.00         0
         343       0.00      0.00      0.00         0
         354       0.00      0.00      0.00         0
         409       0.00      0.00      0.00         0
         414       0.00      0.00      0.00         0
         467       0.00      0.00      0.00         0
         526       1.00      1.00      1.00         1
         538       0.00      0.00      0.00         0
         547       0.00      0.00      0.00         0
         570       0.00      0.00      0.00         0
         571       0.00      0.00      0.00         3
         577       0.00      0.00      0.00         0
         583       0.00      0.00      0.00         0
         587       0.00      0.00      0.00         0
         590       0.00      0.00      0.00         0
         591       0.00      0.00      0.00         0
         593       0.40      0.17      0.24        23
         615       0.00      0.00      0.00         0
         630       0.00      0.00      0.00         3
         638       0.00      0.00      0.00         0
         648       0.00      0.00      0.00         0
         734       0.00      0.00      0.00         0
         781       0.00      0.00      0.00         0
         783       0.00      0.00      0.00         0
         793       0.00      0.00      0.00         0
         796       0.00      0.00      0.00         0
         804       0.00      0.00      0.00         0
         811       0.00      0.00      0.00         0
         814       0.00      0.00      0.00         0
         852       0.00      0.00      0.00         0
         856       0.00      0.00      0.00         0
         881       0.00      0.00      0.00         0
         897       0.00      0.00      0.00         0
         898       0.00      0.00      0.00         0
         912       0.00      0.00      0.00         0
         913       0.00      0.00      0.00         0
         944       0.00      0.00      0.00         0
         994       0.00      0.00      0.00         0
         995       0.00      0.00      0.00         0
        1002       0.00      0.00      0.00         0
        1011       0.00      0.00      0.00         0
        1026       0.00      0.00      0.00         0
        1062       1.00      0.08      0.15        12
        1064       0.00      0.00      0.00         0
        1070       0.00      0.00      0.00         0
        1080       0.00      0.00      0.00         0
        1152       0.00      0.00      0.00         0
        1172       0.00      0.00      0.00         0
        1173       0.00      0.00      0.00         0
        1174       0.00      0.00      0.00         0
        1181       0.00      0.00      0.00         0
        1187       0.00      0.00      0.00         0
        1191       0.00      0.00      0.00         0
        1208       0.00      0.00      0.00         4
        1210       0.00      0.00      0.00         0
        1227       0.00      0.00      0.00         0
        1231       0.00      0.00      0.00         1
        1262       0.00      0.00      0.00         0
        1270       0.00      0.00      0.00         0
        1317       0.00      0.00      0.00         0
        1318       0.00      0.00      0.00         0
        1319       0.00      0.00      0.00         0
        1324       0.00      0.00      0.00         0
        1328       0.00      0.00      0.00         0
        1354       0.00      0.00      0.00         0
        1358       0.00      0.00      0.00         0
        1406       0.00      0.00      0.00         0
        1409       0.00      0.00      0.00         0
        1418       0.83      0.85      0.84        46
        1435       0.00      0.00      0.00         0
        1514       0.00      0.00      0.00         0
        1523       0.00      0.00      0.00         0
        1604       0.00      0.00      0.00         0
        1751       0.00      0.00      0.00         0
        1787       0.00      0.00      0.00         0
        1887       0.00      0.00      0.00         0
        2080       0.00      0.00      0.00         0
        2296       0.00      0.00      0.00         0
        2298       0.00      0.00      0.00         0
        2491       0.00      0.00      0.00         0
        2524       0.00      0.00      0.00         0
        2567       0.00      0.00      0.00         0
        2627       0.00      0.00      0.00         0
        2642       1.00      0.68      0.81        90
        2660       0.00      0.00      0.00         0
        2713       0.00      0.00      0.00         0
        2770       0.98      0.77      0.86       466
        2782       1.00      0.50      0.66       101
        2882       0.40      0.67      0.50         6
        2962       1.00      0.50      0.67        58
        4098       0.00      0.00      0.00         0
        4146       0.00      0.00      0.00         0
        4410       0.00      0.00      0.00         0
        4809       0.00      0.00      0.00         0
        5510       0.00      0.00      0.00         0
        5858       0.00      0.00      0.00         0
        6874       0.00      0.00      0.00         0
        8238       0.00      0.00      0.00         0

    accuracy                           0.89      3504
   macro avg       0.09      0.08      0.08      3504
weighted avg       0.95      0.89      0.91      3504

C:\Users\adity\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\adity\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)